name: Atualizar Leaderboard Automaticamente

# DEPOIS: Roda SOMENTE quando você mandar
on:
  # Permite que você rode esta ação manualmente pela aba "Actions" do GitHub
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout do Repositório
        uses: actions/checkout@v3

      - name: 2. Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Instalar Dependências
        run: pip install pandas jinja2 pytz

      - name: 4. Executar o Script para Gerar o HTML
        run: python main.py

      - name: 5. Fazer Commit e Push do Novo index.html
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add index.html
          # Faz o commit apenas se houver mudanças no index.html
          git diff-index --quiet HEAD || git commit -m "Leaderboard atualizado automaticamente"
          git push